/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as part1GardenAstronautImport } from './routes/(part-1)/garden-astronaut'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const part1GardenAstronautRoute = part1GardenAstronautImport.update({
  id: '/(part-1)/garden-astronaut',
  path: '/garden-astronaut',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(part-1)/garden-astronaut': {
      id: '/(part-1)/garden-astronaut'
      path: '/garden-astronaut'
      fullPath: '/garden-astronaut'
      preLoaderRoute: typeof part1GardenAstronautImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/garden-astronaut': typeof part1GardenAstronautRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/garden-astronaut': typeof part1GardenAstronautRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(part-1)/garden-astronaut': typeof part1GardenAstronautRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/garden-astronaut'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/garden-astronaut'
  id: '__root__' | '/' | '/(part-1)/garden-astronaut'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  part1GardenAstronautRoute: typeof part1GardenAstronautRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  part1GardenAstronautRoute: part1GardenAstronautRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(part-1)/garden-astronaut"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(part-1)/garden-astronaut": {
      "filePath": "(part-1)/garden-astronaut.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
