/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GardenAstronautImport } from './routes/garden-astronaut'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const GardenAstronautRoute = GardenAstronautImport.update({
  id: '/garden-astronaut',
  path: '/garden-astronaut',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/garden-astronaut': {
      id: '/garden-astronaut'
      path: '/garden-astronaut'
      fullPath: '/garden-astronaut'
      preLoaderRoute: typeof GardenAstronautImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/garden-astronaut': typeof GardenAstronautRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/garden-astronaut': typeof GardenAstronautRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/garden-astronaut': typeof GardenAstronautRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/garden-astronaut'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/garden-astronaut'
  id: '__root__' | '/' | '/garden-astronaut'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GardenAstronautRoute: typeof GardenAstronautRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GardenAstronautRoute: GardenAstronautRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/garden-astronaut"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/garden-astronaut": {
      "filePath": "garden-astronaut.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
